### ISSUE TITLE
Substantial decrease in FLOPs per GPU when training multinode

### ISSUE THREAD

**Issue by davidvblumenthal** [EleutherAI/gpt-neox#965]
**Describe the bug**
I can achieve around 160 TFLOPs per GPU using DDP on a single node, however when I use multinode training that number drops to around 65 FLOPs. 
I guess some decrease is expected but less than half doesn't seem right.

Is there anything I am forgetting to specify in the config or has some run into the same issue?

Any help is highly appreciated!

**Environment (please complete the following information):**

I am working on a SLURM cluster which has nodes equipped with 

- 4x A100 per node
- I am using 9 nodes in multinode training (36 GPUs in total)

using this script to start the job:

```bash
#!/bin/bash
#SBATCH --job-name test_training # Name for your job
#SBATCH --nodes=9
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=4:00:00
#SBATCH --mem=200gb
#SBATCH --gpus-per-node=4              # --gres=gpu:4

module purge    

module load compiler/gnu/11 
module load mpi/openmpi/4.1
module load devel/cuda/11.6 



eval "$(conda shell.bash hook)"
conda activate training_main

WORKING_DIR="/home/hk-project-test-lmcdm/ew9122/scratch_training/gpt-verite_"
pushd $WORKING_DIR



echo $(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)

scontrol show hostname $SLURM_JOB_NODELIST | sed 's/$/ slots=4/' > hostfile

GPUS_PER_NODE=4
NNODES=9
export SLURM_NTASKS=$(($GPUS_PER_NODE*$NNODES))

export MASTER_ADDR=$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)
export MASTER_PORT=6000


python ./deepy.py ./train.py -d configs gpt-verite/optimal_models/1-4B.yml
```

and the following training config:
```yaml
{

   "data_path": "/home/hk-project-test-lmcdm/ew9122/scratch_training/data/les_faits_padding_sc2/merged/les_faits",

   "save": "/home/hk-project-test-lmcdm/ew9122/scratch_training/artefacts/checkpoints/gpt-verite_1-4B",
   "load": "/home/hk-project-test-lmcdm/ew9122/scratch_training/artefacts/checkpoints/gpt-verite_1-4B",
   
   "vocab-file": "/home/hk-project-test-lmcdm/ew9122/scratch_training/artefacts/tokenizer/gpt-verite_tokenizer.json",
   "tokenizer_type": "HFTokenizer",

   "pipe-parallel-size": 0,
   "model-parallel-size": 1,


   "train_micro_batch_size_per_gpu": 28,
   "gradient_accumulation_steps": 1,
   "data-impl": "mmap",
   "split": "999,1,0",


   "num-layers": 38,
   "hidden-size": 1664,
   "num-attention-heads": 16,
   "seq-length": 2048,
   "max-position-embeddings": 2048,
   "pos-emb": "rotary",
   "rotary-pct": 0.25,
   "no-weight-tying": true,
   "gpt-j-residual": true,
   "output-layer-parallelism": "column",

   "attention_config": [[["flash"], 38]],
   "scaled_upper_triang_masked_softmax_fusion": true,
   "bias_gelu_fusion": true,
   
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.0002,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8
     }
   },
   "min_lr": 0.00002,



   "init_method_std": 0.02,


   "zero_optimization": {
    "stage": 2,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true
  },

   "checkpoint-activations": true,
   "checkpoint-num-layers": 1,
   "partition-activations": true,
   "synchronize-each-layer": true,

   "gradient_clipping": 1.0,
   "weight-decay": 0.1,
   "hidden-dropout": 0.0,
   "attention-dropout": 0.0,


   "precision": "bfloat16",
   "fp32_allreduce": true,

   "train-iters": 25046, 
   "lr-decay-iters": 25046,

   "distributed-backend": "nccl",
   "lr-decay-style": "cosine",
   "warmup": 0.01,
   "checkpoint-factor": 500,
   "eval-interval": 500,
   "eval-iters": 10,
   "log-interval": 10,
   "steps_per_print": 1,

   "use_wandb": true,
   "wandb_project": "GPT-Verite",
   "wandb_group": "1.4B_GPT-Verite",

   "keep-last-n-checkpoints": 4,
   "wall_clock_breakdown": true,

   "launcher": "slurm",
   "deepspeed_slurm": true,
   "no_ssh_check": true,
   "hostfile": "./hostfile"
}
```
